Repository mlte-team/mlte, pull requests merged in 2023-08, with the labels that each got.

#189 Artifact Store Test Refactor
  test/store/fixture.py
  test/store/test_underlying.py
  test/store/underlying/__init__.py
  test/store/underlying/test_local_memory.py
Labels: testing

#198 Support Implicit Creation of Organizational Elements on Artifact Write
  src/mlte/artifact/artifact.py
  src/mlte/negotiation/negotiation_card.py
  src/mlte/session/state.py
  src/mlte/store/__init__.py
  src/mlte/store/base.py
  src/mlte/store/factory.py
  src/mlte/store/underlying/fs.py
  src/mlte/store/underlying/http.py
  src/mlte/store/underlying/memory.py
  src/mlte/store/util.py
  src/mlte/web/store/api/dependencies.py
  src/mlte/web/store/api/endpoints/artifact.py
  src/mlte/web/store/api/model.py
  src/mlte/web/store/main.py
  src/mlte/web/store/state/state.py
  test/negotiation/test_negotiation_card.py
  test/store/fixture.py
  test/store/test_underlying.py
  test/web/store/test_artifact.py
Labels: enhancement

#205 Refactor to mkdocs
  docs/Makefile
  docs/docs/development.md
  docs/docs/getting_started.md
  docs/docs/index.md
  docs/docs/tutorial0.md
  docs/make.bat
  docs/mkdocs.yml
  docs/requirements.txt
  docs/source/api.rst
  docs/source/conf.py
  docs/source/evidence.md
  docs/source/extending_mlte.md
  docs/source/index.rst
  docs/source/report.md
  docs/source/requirements.md
  docs/source/user_guide.rst
  docs/tools/generate_ref_pages.py
  value.py
Labels: documentation

#217 Add MLTE favicons
  assets/mlte_favicon.ico
  assets/mlte_favicon.png
Labels: enhancement

#232 Transition documentation to diataxis structure
  docs/docs/getting_started.md
  docs/docs/index.md
  docs/docs/mlte_framework.md
  docs/docs/mlte_process_resources.md
  docs/docs/properties.md
  docs/docs/tutorial0.md
  docs/mkdocs.yml
  docs/tools/generate_ref_pages.py
  value.py
Labels: documentation, enhancement

#246 Documentation Updates
  docs/docs/development.md
  docs/docs/getting_started.md
  docs/docs/img/favicon.ico
  docs/docs/index.md
  docs/docs/mlte_framework.md
  docs/docs/mlte_process_resources.md
  docs/docs/mlte_property_resources.md
  docs/docs/properties.md
  docs/docs/tutorial0.md
  docs/docs/using_mlte.md
  docs/mkdocs.yml
Labels: documentation
